// <auto-generated />
using System;
using DT191G_moment34_multipletabledb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DT191Gmoment34multipletabledb.Migrations
{
    [DbContext(typeof(CollectionContext))]
    [Migration("20230213121553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Borrowed", b =>
                {
                    b.Property<int>("BorrowedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FriendId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BorrowedId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("FriendId");

                    b.ToTable("Borrowed");
                });

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongList")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Friends", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FriendId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Borrowed", b =>
                {
                    b.HasOne("DT191G_moment34_multipletabledb.Models.Collection", "Collection")
                        .WithMany("Borrowed")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DT191G_moment34_multipletabledb.Models.Friends", "Friend")
                        .WithMany("Borrowed")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Collection", b =>
                {
                    b.Navigation("Borrowed");
                });

            modelBuilder.Entity("DT191G_moment34_multipletabledb.Models.Friends", b =>
                {
                    b.Navigation("Borrowed");
                });
#pragma warning restore 612, 618
        }
    }
}
